name: geo_env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - geopandas
  - contextily
  - rasterio
  - pyproj
  - matplotlib
  - seaborn
  - jupyterlab
  - jupyter-book
  - myst-nb
  - sphinx
  - notebook
  - ipykernel
  - spyder
  - spyder-kernels=2.5  # Compatible con Spyder 5.x y Python 3.12
  - pandas
  - numpy
  - click
  - pip
  - pip:
      - ghp-import
